import tkinter as tk
from tkinter import messagebox
import mysql.connector







# CREATE TABLE ALVARA (
# ID_ALVARA INT PRIMARY KEY AUTO_INCREMENT,
# NUMERO_ALVARA VARCHAR(20) NOT NULL UNIQUE,
# TIPO_ALVARA VARCHAR(50) NOT NULL,
# DATA_EMISSAO DATE NOT NULL,
# DATA_VALIDADE DATE NOT NULL,
# status ENUM('ativo', 'vencido', 'suspenso', 'cancelado') DEFAULT 'ativo',
# DESCRICAO TEXT,
# DOCUMENTO_ANEXO LONGBLOB,
# CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
# ATUALIZADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP